config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'user/:id', to: 'users#show', as: 'user'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/home.html.erb
<div class="container py-5 h-100">
  <div class="row d-flex justify-content-center align-items-center h-100" style="padding-top: 10%">
    <div class="col-lg-8 col-xl-6">
      <div class="card rounded-3">
        <div class="card-body p-2 p-md-3"><br />
          <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2 text-center">Friendsenger</h3>
          <% if current_user %>
            <h4>Welcome <%= current_user.email %></h4><br />
            <%= image_tag(current_user.avatar_thumbnail) %><br><br>
            <div class="btn-group">
              <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-secondary"%>&nbsp;
              <%= link_to "Account Settings", edit_user_registration_path, class: "btn btn-primary" %>&nbsp;
              <%= link_to "Start Chatting", rooms_path, class: "btn btn-success"%>
            </div>
          <% else %>
<!--            <%#= image_tag "home.jpg", class: "logo"%><br><br>-->
            <div class="btn-group">
              <%= link_to "Login", new_user_session_path, class: "btn btn-primary"%>&nbsp;
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<style>
    @media (min-width: 1025px) {
        .h-custom {
            height: 100vh !important;
        }
    }

    body
    {
        background-color: lightslategrey;
    }
    .footer-red-bar
    {
        width: 100%;
        height: 180px;
        margin: 0 auto;
        margin-top: 2em;
    }

    .footer-red-bar img
    {
        width: 100%;
        height: 180px;
        object-fit: cover;
        object-position: top;
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
    }
</style>